name: test

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.os }}
    name: "Node ${{ matrix.node }} / ${{ matrix.os }}"
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [18.x, 20.x]
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
        with:
          fetch-depth: 1
          persist-credentials: false
      - uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2.5.2
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - name: Run test
        run: |
          npm ci
          npm test
